version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  postgresql-tradesdb:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=trades_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=tradesdb
      - POSTGRESQL_POSTGRES_PASSWORD=password123
  postgresql-servingdb:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=serving_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=servingdb
      - POSTGRESQL_POSTGRES_PASSWORD=password123

  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: 'influxdb'
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=market_data_load_monitoring
      - INFLUXDB_USER=market_monitoring
      - INFLUXDB_USER_PASSWORD=password123
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=32sd33asd21df987as
      - INFLUXDB_ADMIN_USER_TOKEN=dsfsdf1jdhadjan54skdnajsbd123jasbdjas
    volumes:
      - influxdb-volume:/var/lib/influxdb
  sse:
    build:
      context: .
      dockerfile: Dockerfile-sse
    restart: always
    depends_on:
      - postgresql-tradesdb
      - kafka


volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true