FROM bitnami/spark:2.4.6
RUN mkdir /opt/app
COPY ./market-data-loader/target/market-data-loader-jar-with-dependencies.jar /opt/app
COPY ./market-data-loader/conf/log4j.properties /opt/app
COPY ./market-data-loader/conf/mdl.properties /opt/app
COPY ./market-data-loader/shell/run.sh /opt/app
RUN cd /opt/app
WORKDIR /opt/app
CMD ["./run.sh", "io.github.tankist88.mdle.mdl.load.MarketDataReader", "512m", "512m", "1", "client"]