CREATE TABLE CANDLES (
      DATETIME TIMESTAMP,
      TICKER VARCHAR (20),
      OPEN NUMERIC (10, 2),
      HIGH NUMERIC (10, 2),
      LOW NUMERIC (10, 2),
      CLOSE NUMERIC (10, 2),
      VALUE NUMERIC (10, 2),
      PRIMARY KEY (DATETIME, TICKER)
);

GRANT ALL PRIVILEGES ON DATABASE servingdb to serving_user;
GRANT ALL PRIVILEGES ON TABLE CANDLES TO serving_user;