CREATE TABLE CANDLES (
      DATETIME TIMESTAMP,
      TICKER VARCHAR (20),
      OPEN NUMERIC (10, 2),
      HIGH NUMERIC (10, 2),
      LOW NUMERIC (10, 2),
      CLOSE NUMERIC (10, 2),
      VALUE NUMERIC (10, 2),
      PRIMARY KEY (DATETIME, TICKER)
);