CREATE TABLE CANDLES_STREAM (
    DATETIME TIMESTAMP,
    TICKER VARCHAR (20),
    OPEN NUMERIC (10, 2),
    HIGH NUMERIC (10, 2),
    LOW NUMERIC (10, 2),
    CLOSE NUMERIC (10, 2),
    VALUE NUMERIC (10, 2),
    PRIMARY KEY (DATETIME, TICKER)
);

CREATE TABLE CANDLES (
    DATETIME TIMESTAMP,
    TICKER VARCHAR (20),
    OPEN NUMERIC (10, 2),
    HIGH NUMERIC (10, 2),
    LOW NUMERIC (10, 2),
    CLOSE NUMERIC (10, 2),
    VALUE NUMERIC (10, 2),
    PRIMARY KEY (DATETIME, TICKER)
);

CREATE TABLE OFFSET_CHECKPOINT (
    APP_NAME VARCHAR (120),
    TOPIC VARCHAR (100),
    PART INT,
    LAST_OFFSET BIGINT,
    PRIMARY KEY (APP_NAME, TOPIC, PART)
);

CREATE TABLE CLUSTER_APP_STATE (
    APP_NAME VARCHAR (120),
    APP_STATE VARCHAR (10),
    LAST_MODIFIED TIMESTAMP,
    PRIMARY KEY (APP_NAME)
);

GRANT ALL PRIVILEGES ON DATABASE servingdb to serving_user;
GRANT ALL PRIVILEGES ON TABLE CANDLES TO serving_user;
GRANT ALL PRIVILEGES ON TABLE CANDLES_STREAM TO serving_user;
GRANT ALL PRIVILEGES ON TABLE OFFSET_CHECKPOINT TO serving_user;
GRANT ALL PRIVILEGES ON TABLE CLUSTER_APP_STATE TO serving_user;